# ref. https://goreleaser.com/customization/build/
builds:
  - id: spaces-cli
    main: ./cmd/spaces-cli
    binary: spaces-cli
    flags:
      - -v
    # TODO: remove this once we support 32-bit in avalanchego
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: freebsd
        goarch: 386
  - id: spacesvm
    main: ./cmd/spacesvm
    binary: spacesvm
    flags:
      - -v
    # TODO: remove this once we support 32-bit in avalanchego
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: freebsd
        goarch: 386

release:
  github:
    owner: ava-labs
    name: spacesvm
